[versions]
agp = "9.0.0"
kotlin = "2.3.0"
jvmToolchain = "17"
pluginVersion = "0.9.6"

[plugins]
android-gradle = { id = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
